APPNAME = sinuous_waves

OF_ROOT ?= ../../..
PROJECT_ROOT = .

PROJECT_CFLAGS =
PROJECT_CXXFLAGS = -std=c++17
PROJECT_LDFLAGS =

PROJECT_EXTERNAL_SOURCE_PATHS =
PROJECT_EXTERNAL_SOURCE_FILES =
PROJECT_EXTERNAL_LINK_LIBS =
PROJECT_EXTERNAL_LINK_FLAGS =

PROJECT_BUILD_DIR = bin
